# Generated by Django 3.2.18 on 2023-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basigo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='products_of_interest',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
