# Generated by Django 3.2.18 on 2023-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basigo', '0002_auto_20230323_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
