# Generated by Django 3.2.18 on 2023-03-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basigo', '0004_alter_customer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
    ]
