# Generated by Django 3.2.18 on 2023-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basigo', '0005_auto_20230323_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.CharField(blank=True, choices=[('A', 'Product A (for annual income of at least 10,000)'), ('B', 'Product B (for annual income of at least 20,000)'), ('C', 'Product C (for annual income of at least 30,000)')], max_length=255),
        ),
    ]
