# Generated by Django 3.2.18 on 2023-03-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basigo', '0006_customer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
